sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gloud config set project multi-k8s-311115
  - gcloud config set compute/zone europe-west1-b
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t danielchrislucas/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true danielchrislucas/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
